const reporter = require('cucumber-html-reporter');
// import { CommonUtil } from "../common/common-util";
const fs = require('fs');
const path = require('path');

const baseReportsDir = 'reports';

// Read the latest timestamped folder generated by cucumber.js
const latest = JSON.parse(
  fs.readFileSync(path.join(baseReportsDir, 'latest.json'), 'utf8')
);
const testReportFolder = latest.testReportFolder;

// Ensure directory exists
if (!fs.existsSync(testReportFolder)) {
  console.error(`Report folder not found: ${testReportFolder}`);
  process.exit(1);
}

// Get Browser Type from XML Data
// const browserType = String(CommonUtil.getXmlData('BrowserType'));

// Define the report paths inside the same timestamped folder
const jsonReportPath = path.join(testReportFolder, 'report.json');
const xmlReportPath = path.join(testReportFolder, 'report.xml');
const htmlReportPath = path.join(
  testReportFolder,
  `cucumber_reporter_${Date.now()}.html`
);

// Define Cucumber HTML Reporter options
const options = {
  theme: 'bootstrap',
  jsonFile: jsonReportPath,
  xmlFile: xmlReportPath,
  output: htmlReportPath,
  reportSuiteAsScenarios: true,
  launchReport: false,
  metadata: {
    'App Version': '0.3.2',
    'Test Environment': 'STAGING',
    // Browser: browserType,
    Platform: 'Windows 10',
    Parallel: 'Scenarios',
    Executed: 'Remote',
  },
};

// Generate the HTML report
reporter.generate(options);

console.log(`HTML Report generated: ${htmlReportPath}`);
